// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:darbak/modules/home/all_branching/data/models/branch_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AfternoneAdapter());
    registerAdapter(AlldaysAdapter());
    registerAdapter(BranchCenterAdapter());
    registerAdapter(BranchModelAdapter());
    registerAdapter(FriAdapter());
    registerAdapter(MonAdapter());
    registerAdapter(PolygonPointAdapter());
    registerAdapter(WorkTimeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AfternoneAdapter());
    registerAdapter(AlldaysAdapter());
    registerAdapter(BranchCenterAdapter());
    registerAdapter(BranchModelAdapter());
    registerAdapter(FriAdapter());
    registerAdapter(MonAdapter());
    registerAdapter(PolygonPointAdapter());
    registerAdapter(WorkTimeAdapter());
  }
}
